apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  sources:
    # 1) Helm chart source
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 61.7.0
      helm:
        releaseName: monitoring
        skipCrds: false
        valueFiles:
          - $values/apps/monitoring/helm/values.yaml

    # 2) Your Git repo source (values + ingress + namespace)
    - repoURL: https://github.com/sanjay-k598/homelab-gitops.git
      targetRevision: main
      ref: values
      path: apps/monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
