apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  # MULTI-SOURCE: Helm chart + Git values
  sources:
    # 1️⃣ Helm chart source
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 80.6.0
      helm:
        releaseName: monitoring
        skipCrds: false
        valueFiles:
          - $values/apps/monitoring/values.yaml

    # 2️⃣ Git repo containing values.yaml
    - repoURL: https://github.com/sanjay-k598/homelab-gitops.git
      targetRevision: main
      ref: values

  # Ignore CRD annotation bloat (your earlier fix)
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations
        - /metadata/managedFields

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
